import { StyleSheet } from "react-native";
import Colors from "./Colors";

const getStyles = (width, height) => {
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.containerBackground,
      paddingHorizontal: 10,
      paddingTop: width > 400 ? 30 : 15,
      paddingBottom: width > 400 ? 2 : 10,
      // borderStyle: "dotted",
      // borderWidth: 2,
    },
    mainGameArea: {
      flexDirection: width > 400 ? "row" : "column",
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      padding: 15,
      top: width > 400 ? 30 : 0,
      // backgroundColor: "blue",
    },
    computerSection: {
      alignItems: "center",
      width: width > 400 ? 280 : "100%",
      backgroundColor: Colors.opponentAreaBackground,
      flex: width > 400 ? 1.5 : 1,
      borderRadius: 20,
    },
    humanSection: {
      alignItems: "center",
      width: width > 400 ? 280 : "100%",
      backgroundColor: Colors.humanAreaBackground,
      flex: width > 400 ? 1.5 : 1,
      borderRadius: 20,
    },
    sectionHeader: {
      fontSize: 18,
      fontWeight: "600",
      marginBottom: 5,
      color: Colors.mainTextColor,
      textAlign: "center",
      left: 8,
    },
    hand: {
      flexDirection: "row",
    },
    cardBack: {
      margin: 5,
      backgroundColor: Colors.cardBackBackground,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors.cardBackBorder,
      alignItems: "center",
      justifyContent: "center",
      height: 70,
      width: 45,
    },
    deckCardBack: {
      margin: 5,
      backgroundColor: Colors.cardBackBackground,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors.cardBackBorder,
      alignItems: "center",
      justifyContent: "center",
      height: 60,
      width: 40,
      position: "absolute",
    },
    cardBackText: {
      fontSize: 50,
      color: "#fff",
    },
    playText: {
      fontSize: 15,
      marginVertical: 2,
    },
    roundText: {
      fontSize: 18,
      textAlign: "center",
    },
    newGameButton: {
      backgroundColor: Colors.buttonBackground,
      paddingVertical: 5,
      paddingHorizontal: 25,
      borderRadius: 8,
      alignSelf: "center",
      justifyContent: "center",
      alignContent: "center",
      alignItems: "center",
    },
    newGameText: {
      color: "#fff",
      fontSize: 18,
      textAlign: "center",
    },
    gameResultSection: {
      flex: 2,
      justifyContent: "center",
      alignItems: "center",
      bottom: width > 400 ? 40 : 0,
      // backgroundColor: "red",
      marginTop: 8,
      gap: width > 400 ? 30 : 5,
    },
    message: {
      fontSize: 16,
      textAlign: "center",
      color: Colors.mainTextColor,
    },
    messageContainer: {
      bottom: 10,
      width: 330,
      padding: 5,
      backgroundColor: Colors.logContainerBackground,
      borderRadius: 15,
    },
    currentRound: {
      fontSize: 18,
      textAlign: "center",
      flexDirection: width > 400 || height < 640 ? "row" : "column",
      flexWrap: "wrap",
      gap: 30,
      justifyContent: "center",
      alignItems: "center",
      // backgroundColor: "blue",
      // flex: 1,
    },
    controlText: {
      fontSize: 18,
      textAlign: "center",
      marginVertical: 5,
    },
    animationOverlay: {
      position: "absolute",
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      justifyContent: "center",
      alignItems: "center",
      zIndex: 100,
      backgroundColor: "rgba(0,0,0,0.5)",
    },
    dealingText: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#333",
      backgroundColor: "rgba(255,255,255,0.9)",
      padding: 15,
      borderRadius: 10,
    },
    shuffleContainer: {
      alignItems: "center",
      justifyContent: "center",
      padding: 20,
      backgroundColor: "rgba(255,255,255,0.9)",
      borderRadius: 10,
      elevation: 5,
    },
    shuffleText: {
      fontSize: 24,
      fontWeight: "bold",
      marginBottom: 20,
      color: "#333",
    },
    shuffleCard: {
      position: "absolute",
      width: 45,
      height: 70,
      backgroundColor: Colors.cardBackBackground,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: Colors.cardBackBorder,
      justifyContent: "center",
      alignItems: "center",
      alignSelf: "center",
    },
    shuffleCards: {
      width: 100,
      height: 100,
    },
    // Add these to your styles object in getStyles
    controlsButton: {
      // position: "absolute",
      // bottom: 20,
      // right: 20,
      width: 40,
      height: 40,
      borderRadius: 30,
      backgroundColor: Colors.buttonBackground,
      justifyContent: "center",
      alignItems: "center",
      elevation: 5,
    },
    overlayContainer: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 1000,
    },
    overlayContent: {
      width: "80%",
      backgroundColor: "#0a8132",
      borderRadius: 16,
      padding: 20,
      borderWidth: 2,
      borderColor: "#e0f2e9",
    },
    overlayHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    overlayTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#FFFFFF",
    },
    overlayButtonText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "bold",
    },
    startButton: {
      backgroundColor: "#FF9800",
      borderRadius: 25,
      paddingVertical: 5,
      paddingHorizontal: 10,
    },
  });
  return styles;
};

export default getStyles;
