import { StyleSheet } from "react-native";
import Colors from "./Colors";

const getStyles = (width: number, height: number) => {
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.containerBackground,
      paddingHorizontal: 10,
      paddingTop: width > 400 ? 30 : 15,
      paddingBottom: width > 400 ? 2 : 10,
      // borderStyle: "dotted",
      // borderWidth: 2,
    },
    mainGameArea: {
      flexDirection: width > 400 ? "row" : "column",
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      padding: 15,
      top: width > 400 ? 30 : 0,
      // backgroundColor: "blue",
    },
    computerSection: {
      alignItems: "center",
      width: width > 400 ? 280 : "100%",
      backgroundColor: Colors.opponentAreaBackground,
      flex: width > 400 ? 1.5 : 1,
      borderRadius: 20,
    },
    humanSection: {
      alignItems: "center",
      width: width > 400 ? 280 : "100%",
      backgroundColor: Colors.humanAreaBackground,
      flex: width > 400 ? 1.5 : 1,
      borderRadius: 20,
    },
    sectionHeader: {
      fontSize: 18,
      fontWeight: "600",
      marginBottom: 5,
      color: Colors.mainTextColor,
      textAlign: "center",
      left: 8,
    },
    hand: {
      flexDirection: "row",
    },
    gameResultSection: {
      flex: 2,
      justifyContent: "center",
      alignItems: "center",
      bottom: width > 400 ? 40 : 0,
      // backgroundColor: "red",
      marginTop: 8,
      gap: width > 400 ? 30 : 5,
    },
    message: {
      fontSize: 16,
      textAlign: "center",
      color: Colors.mainTextColor,
    },
    messageContainer: {
      bottom: 10,
      width: 330,
      padding: 5,
      backgroundColor: Colors.logContainerBackground,
      borderRadius: 15,
      elevation: 5,
    },
    currentRound: {
      fontSize: 18,
      textAlign: "center",
      flexDirection: width > 400 || height < 640 ? "row" : "column",
      flexWrap: "wrap",
      gap: 30,
      justifyContent: "center",
      alignItems: "center",
      // backgroundColor: "blue",
      // flex: 1,
    },
    animationOverlay: {
      position: "absolute",
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      justifyContent: "center",
      alignItems: "center",
      zIndex: 100,
      backgroundColor: "rgba(0,0,0,0.5)",
    },
    dealingText: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#333",
      backgroundColor: "rgba(255,255,255,0.9)",
      padding: 15,
      borderRadius: 10,
    },

    overlayContainer: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 1000,
    },
    overlayContent: {
      width: "80%",
      backgroundColor: "#0a8132",
      borderRadius: 16,
      padding: 20,
      borderWidth: 2,
      borderColor: "#e0f2e9",
    },
    overlayHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    overlayTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#FFFFFF",
    },
    overlayButtonText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "bold",
    },
    startButton: {
      backgroundColor: "#FF9800",
      borderRadius: 25,
      paddingVertical: 5,
      paddingHorizontal: 10,
      elevation: 2,
    },
    decorationContainer: {
      ...StyleSheet.absoluteFillObject,
      overflow: "hidden",
      opacity: 0.3,
    },
    cardDecoration: {
      position: "absolute",
      width: 80,
      height: 110,
      borderRadius: 10,
      backgroundColor: "red",
      borderWidth: 2,
      borderColor: "rgba(255, 255, 255, 0.5)",
    },
    leaveButton: {
      backgroundColor: "#f44336",
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 8,
      alignSelf: "center",
      marginTop: 10,
    },
    leaveButtonText: {
      color: "white",
      fontWeight: "bold",
    },
  });
  return styles;
};

export default getStyles;
